services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: jenkins
    restart: always
    user: root

    group_add:
      - 1000

    ports:
      - "8081:8080"      # Jenkins UI
      - "50000:50000"    # Agent port

    environment:
      # MLflow Tracking Server URL
      MLFLOW_URI: "http://host.docker.internal:5000"

    volumes:
      # Persistent Jenkins data
      - jenkins_home:/var/jenkins_home

      # Allow Jenkins to execute docker commands
      - /var/run/docker.sock:/var/run/docker.sock

      # ---------------------------------------------
      #  Airflow DAGs mount (relative safe mapping)
      # ---------------------------------------------
      - ../fir-mlops/airflow/dags:/airflow-dags
      # This maps to:
      # /Volumes/Development/mechinelearning-project/fir-mlops/airflow/dags

volumes:
  jenkins_home:
    name: jenkins_home
